#define NL                               1
#define L_BRACE                          2
#define R_BRACE                          3
#define SEMICOLON                        4
#define ACTOR                            5
#define COLON                            6
#define OBITUARY                         7
#define HITOBITUARY                      8
#define MODEL                            9
#define HEALTH                          10
#define REACTIONTIME                    11
#define PAINCHANCE                      12
#define SPEED                           13
#define DAMAGE                          14
#define RADIUS                          15
#define HEIGHT                          16
#define MASS                            17
#define SEESOUND                        18
#define ATTACKSOUND                     19
#define PAINSOUND                       20
#define DEATHSOUND                      21
#define ACTIVESOUND                     22
#define CLEARFLAGS                      23
#define MONSTER                         24
#define PROJECTILE                      25
#define PLUS                            26
#define MINUS                           27
#define STATES                          28
#define LOOP                            29
#define STOP                            30
#define GOTO                            31
#define STR                             32
#define INT                             33
#define FLOAT                           34
