#define L_BRACE                          1
#define R_BRACE                          2
#define SHADER                           3
#define SEMICOLON                        4
#define V_SOURCE                         5
#define F_SOURCE                         6
#define MATERIAL                         7
#define SPRITE                           8
#define COLON                            9
#define SHADER_REF                      10
#define TEX_UNIT                        11
#define TEXTURE                         12
#define WORLDSIZE                       13
#define SCALE                           14
#define TEXELOFFSETS                    15
#define OFFSET                          16
#define FILTERING                       17
#define MAX_ANISOTROPY                  18
#define STR                             19
#define INT                             20
#define FLOAT                           21
