/* This file is automatically generated by Lemon from input grammar
** source file "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y".
*/
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 46 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"

#include <cctype>
#include "i_video.h"
#include "z_zone.h"
#include "parser_driver.h"
#include "ntexture.parser.h"
#line 37 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#ifndef L_BRACE
#define L_BRACE                         1
#define R_BRACE                         2
#define SHADER                          3
#define SEMICOLON                       4
#define V_SOURCE                        5
#define F_SOURCE                        6
#define MATERIAL                        7
#define SPRITE                          8
#define COLON                           9
#define SHADER_REF                     10
#define TEX_UNIT                       11
#define TEXTURE                        12
#define WORLDSIZE                      13
#define SCALE                          14
#define TEXELOFFSETS                   15
#define OFFSET                         16
#define FILTERING                      17
#define MAX_ANISOTROPY                 18
#define STR                            19
#define INT                            20
#define FLOAT                          21
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    NTEXTURE_ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is NTEXTURE_ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    NTEXTURE_ParseARG_SDECL     A static variable declaration for the %extra_argument
**    NTEXTURE_ParseARG_PDECL     A parameter declaration for the %extra_argument
**    NTEXTURE_ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    NTEXTURE_ParseARG_STORE     Code to store %extra_argument into yypParser
**    NTEXTURE_ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    NTEXTURE_ParseCTX_*         As NTEXTURE_ParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 41
#define YYACTIONTYPE unsigned char
#define NTEXTURE_ParseTOKENTYPE yy_t
typedef union {
  int yyinit;
  NTEXTURE_ParseTOKENTYPE yy0;
  float yy1;
  const char * yy10;
  int yy34;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#define NTEXTURE_ParseARG_SDECL ntexture_driver *d;
#define NTEXTURE_ParseARG_PDECL ,ntexture_driver *d
#define NTEXTURE_ParseARG_PARAM ,d
#define NTEXTURE_ParseARG_FETCH ntexture_driver *d=yypParser->d;
#define NTEXTURE_ParseARG_STORE yypParser->d=d;
#define NTEXTURE_ParseCTX_SDECL
#define NTEXTURE_ParseCTX_PDECL
#define NTEXTURE_ParseCTX_PARAM
#define NTEXTURE_ParseCTX_FETCH
#define NTEXTURE_ParseCTX_STORE
#define YYNSTATE             35
#define YYNRULE              37
#define YYNRULE_WITH_ACTION  24
#define YYNTOKEN             22
#define YY_MAX_SHIFT         34
#define YY_MIN_SHIFTREDUCE   67
#define YY_MAX_SHIFTREDUCE   103
#define YY_ERROR_ACTION      104
#define YY_ACCEPT_ACTION     105
#define YY_NO_ACTION         106
#define YY_MIN_REDUCE        107
#define YY_MAX_REDUCE        143
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (72)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   133,   34,   77,  105,    1,   67,  143,    6,   69,   70,
 /*    10 */   111,   28,   18,   14,   12,   17,   11,   16,    9,  131,
 /*    20 */     5,    5,   20,   72,   82,   87,   73,   74,   99,  141,
 /*    30 */    31,   19,   78,   96,  135,    2,  111,  115,   90,   89,
 /*    40 */    90,   89,    4,    3,   88,   25,   24,  138,   87,   26,
 /*    50 */    33,   10,    8,   86,   29,   13,   15,   85,   27,   30,
 /*    60 */    32,  108,   84,   83,   81,    7,   80,   79,   21,   76,
 /*    70 */    22,   23,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */    27,   28,    2,   25,   26,    2,   40,   34,    5,    6,
 /*    10 */    22,   24,   12,   13,   14,   15,   16,   17,   18,    0,
 /*    20 */    32,   33,    3,    2,    4,   19,    7,    8,    9,   37,
 /*    30 */    38,   10,   11,    4,   30,   31,   22,   22,   20,   21,
 /*    40 */    20,   21,   29,   36,   20,   22,   24,   33,   19,   24,
 /*    50 */    35,   24,   24,    4,   24,   24,   22,    4,   23,   22,
 /*    60 */    22,   22,    4,    4,    4,   39,    4,    4,    1,    4,
 /*    70 */     1,    1,   41,   41,   41,   41,   41,   41,   41,   41,
 /*    80 */    41,   41,   41,   41,   41,   41,   41,   41,   41,   41,
 /*    90 */    41,   41,   41,   41,
};
#define YY_SHIFT_COUNT    (34)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (70)
static const unsigned char yy_shift_ofst[] = {
 /*     0 */    72,   19,    6,   21,    3,   29,    6,    0,   20,   18,
 /*    10 */    18,   18,   18,   18,   18,    6,    6,   24,    6,    6,
 /*    20 */     6,   72,   72,   72,   49,   53,   58,   59,   60,   62,
 /*    30 */    63,   67,   65,   69,   70,
};
#define YY_REDUCE_COUNT (23)
#define YY_REDUCE_MIN   (-34)
#define YY_REDUCE_MAX   (39)
static const signed char yy_reduce_ofst[] = {
 /*     0 */   -22,  -27,  -12,   -8,    4,   14,   15,  -34,  -13,   22,
 /*    10 */    25,   27,   28,   30,   31,   23,   34,   35,   37,   38,
 /*    20 */    39,   26,    7,   13,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   132,  104,  104,  104,  104,  104,  104,  104,  104,  104,
 /*    10 */   104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
 /*    20 */   104,  142,  140,  134,  104,  104,  104,  104,  104,  104,
 /*    30 */   104,  104,  104,  104,  104,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  NTEXTURE_ParseARG_SDECL                /* A place to hold %extra_argument */
  NTEXTURE_ParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#include <assert.h>
#ifndef NDEBUG
#include <stdio.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void NTEXTURE_ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "L_BRACE",
  /*    2 */ "R_BRACE",
  /*    3 */ "SHADER",
  /*    4 */ "SEMICOLON",
  /*    5 */ "V_SOURCE",
  /*    6 */ "F_SOURCE",
  /*    7 */ "MATERIAL",
  /*    8 */ "SPRITE",
  /*    9 */ "COLON",
  /*   10 */ "SHADER_REF",
  /*   11 */ "TEX_UNIT",
  /*   12 */ "TEXTURE",
  /*   13 */ "WORLDSIZE",
  /*   14 */ "SCALE",
  /*   15 */ "TEXELOFFSETS",
  /*   16 */ "OFFSET",
  /*   17 */ "FILTERING",
  /*   18 */ "MAX_ANISOTROPY",
  /*   19 */ "STR",
  /*   20 */ "INT",
  /*   21 */ "FLOAT",
  /*   22 */ "str",
  /*   23 */ "int",
  /*   24 */ "num",
  /*   25 */ "start",
  /*   26 */ "definitions",
  /*   27 */ "def",
  /*   28 */ "shader_name",
  /*   29 */ "shader_props",
  /*   30 */ "shader_prop",
  /*   31 */ "shader_sourcetype",
  /*   32 */ "shader_sources",
  /*   33 */ "shader_src",
  /*   34 */ "mat_type",
  /*   35 */ "mat_name",
  /*   36 */ "mat_props",
  /*   37 */ "mat_prop",
  /*   38 */ "tex_unit",
  /*   39 */ "tex_props",
  /*   40 */ "tex_prop",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "def ::= shader_name L_BRACE shader_props R_BRACE",
 /*   1 */ "shader_name ::= SHADER str",
 /*   2 */ "shader_sourcetype ::= V_SOURCE",
 /*   3 */ "shader_sourcetype ::= F_SOURCE",
 /*   4 */ "shader_src ::= str",
 /*   5 */ "def ::= mat_type mat_name L_BRACE mat_props R_BRACE",
 /*   6 */ "mat_type ::= MATERIAL",
 /*   7 */ "mat_type ::= SPRITE",
 /*   8 */ "mat_name ::= str",
 /*   9 */ "mat_prop ::= SHADER_REF str SEMICOLON",
 /*  10 */ "mat_prop ::= tex_unit L_BRACE tex_props R_BRACE",
 /*  11 */ "tex_unit ::= TEX_UNIT",
 /*  12 */ "tex_prop ::= TEXTURE str SEMICOLON",
 /*  13 */ "tex_prop ::= WORLDSIZE num num SEMICOLON",
 /*  14 */ "tex_prop ::= SCALE num num SEMICOLON",
 /*  15 */ "tex_prop ::= SCALE num SEMICOLON",
 /*  16 */ "tex_prop ::= TEXELOFFSETS int SEMICOLON",
 /*  17 */ "tex_prop ::= OFFSET num num SEMICOLON",
 /*  18 */ "tex_prop ::= FILTERING str str SEMICOLON",
 /*  19 */ "tex_prop ::= MAX_ANISOTROPY num SEMICOLON",
 /*  20 */ "str ::= STR",
 /*  21 */ "int ::= INT",
 /*  22 */ "num ::= FLOAT",
 /*  23 */ "num ::= INT",
 /*  24 */ "start ::= definitions",
 /*  25 */ "definitions ::=",
 /*  26 */ "definitions ::= definitions def",
 /*  27 */ "shader_props ::=",
 /*  28 */ "shader_props ::= shader_props shader_prop",
 /*  29 */ "shader_prop ::= shader_sourcetype shader_sources SEMICOLON",
 /*  30 */ "shader_sources ::= shader_src",
 /*  31 */ "shader_sources ::= shader_sources shader_src",
 /*  32 */ "def ::= COLON",
 /*  33 */ "mat_props ::=",
 /*  34 */ "mat_props ::= mat_props mat_prop",
 /*  35 */ "tex_props ::=",
 /*  36 */ "tex_props ::= tex_props tex_prop",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to NTEXTURE_ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void NTEXTURE_ParseInit(void *yypRawParser NTEXTURE_ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  NTEXTURE_ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef NTEXTURE_Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to NTEXTURE_Parse and NTEXTURE_ParseFree.
*/
void *NTEXTURE_ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) NTEXTURE_ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    NTEXTURE_ParseCTX_STORE
    NTEXTURE_ParseInit(yypParser NTEXTURE_ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* NTEXTURE_Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  NTEXTURE_ParseARG_FETCH
  NTEXTURE_ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
      /* TERMINAL Destructor */
    case 1: /* L_BRACE */
    case 2: /* R_BRACE */
    case 3: /* SHADER */
    case 4: /* SEMICOLON */
    case 5: /* V_SOURCE */
    case 6: /* F_SOURCE */
    case 7: /* MATERIAL */
    case 8: /* SPRITE */
    case 9: /* COLON */
    case 10: /* SHADER_REF */
    case 11: /* TEX_UNIT */
    case 12: /* TEXTURE */
    case 13: /* WORLDSIZE */
    case 14: /* SCALE */
    case 15: /* TEXELOFFSETS */
    case 16: /* OFFSET */
    case 17: /* FILTERING */
    case 18: /* MAX_ANISOTROPY */
    case 19: /* STR */
    case 20: /* INT */
    case 21: /* FLOAT */
{
#line 40 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
 if (yymajor == STR) Z_Free(const_cast<char*>((yypminor->yy0).stype)); 
#line 609 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
}
      break;
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void NTEXTURE_ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef NTEXTURE_Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void NTEXTURE_ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  NTEXTURE_ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* NTEXTURE_Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int NTEXTURE_ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int NTEXTURE_ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   NTEXTURE_ParseARG_FETCH
   NTEXTURE_ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
#line 35 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"

  fprintf(stderr,"Giving up.  Parser stack overflow.\n");
#line 830 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
/******** End %stack_overflow code ********************************************/
   NTEXTURE_ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   NTEXTURE_ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  NTEXTURE_ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    27,  /* (0) def ::= shader_name L_BRACE shader_props R_BRACE */
    28,  /* (1) shader_name ::= SHADER str */
    31,  /* (2) shader_sourcetype ::= V_SOURCE */
    31,  /* (3) shader_sourcetype ::= F_SOURCE */
    33,  /* (4) shader_src ::= str */
    27,  /* (5) def ::= mat_type mat_name L_BRACE mat_props R_BRACE */
    34,  /* (6) mat_type ::= MATERIAL */
    34,  /* (7) mat_type ::= SPRITE */
    35,  /* (8) mat_name ::= str */
    37,  /* (9) mat_prop ::= SHADER_REF str SEMICOLON */
    37,  /* (10) mat_prop ::= tex_unit L_BRACE tex_props R_BRACE */
    38,  /* (11) tex_unit ::= TEX_UNIT */
    40,  /* (12) tex_prop ::= TEXTURE str SEMICOLON */
    40,  /* (13) tex_prop ::= WORLDSIZE num num SEMICOLON */
    40,  /* (14) tex_prop ::= SCALE num num SEMICOLON */
    40,  /* (15) tex_prop ::= SCALE num SEMICOLON */
    40,  /* (16) tex_prop ::= TEXELOFFSETS int SEMICOLON */
    40,  /* (17) tex_prop ::= OFFSET num num SEMICOLON */
    40,  /* (18) tex_prop ::= FILTERING str str SEMICOLON */
    40,  /* (19) tex_prop ::= MAX_ANISOTROPY num SEMICOLON */
    22,  /* (20) str ::= STR */
    23,  /* (21) int ::= INT */
    24,  /* (22) num ::= FLOAT */
    24,  /* (23) num ::= INT */
    25,  /* (24) start ::= definitions */
    26,  /* (25) definitions ::= */
    26,  /* (26) definitions ::= definitions def */
    29,  /* (27) shader_props ::= */
    29,  /* (28) shader_props ::= shader_props shader_prop */
    30,  /* (29) shader_prop ::= shader_sourcetype shader_sources SEMICOLON */
    32,  /* (30) shader_sources ::= shader_src */
    32,  /* (31) shader_sources ::= shader_sources shader_src */
    27,  /* (32) def ::= COLON */
    36,  /* (33) mat_props ::= */
    36,  /* (34) mat_props ::= mat_props mat_prop */
    39,  /* (35) tex_props ::= */
    39,  /* (36) tex_props ::= tex_props tex_prop */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -4,  /* (0) def ::= shader_name L_BRACE shader_props R_BRACE */
   -2,  /* (1) shader_name ::= SHADER str */
   -1,  /* (2) shader_sourcetype ::= V_SOURCE */
   -1,  /* (3) shader_sourcetype ::= F_SOURCE */
   -1,  /* (4) shader_src ::= str */
   -5,  /* (5) def ::= mat_type mat_name L_BRACE mat_props R_BRACE */
   -1,  /* (6) mat_type ::= MATERIAL */
   -1,  /* (7) mat_type ::= SPRITE */
   -1,  /* (8) mat_name ::= str */
   -3,  /* (9) mat_prop ::= SHADER_REF str SEMICOLON */
   -4,  /* (10) mat_prop ::= tex_unit L_BRACE tex_props R_BRACE */
   -1,  /* (11) tex_unit ::= TEX_UNIT */
   -3,  /* (12) tex_prop ::= TEXTURE str SEMICOLON */
   -4,  /* (13) tex_prop ::= WORLDSIZE num num SEMICOLON */
   -4,  /* (14) tex_prop ::= SCALE num num SEMICOLON */
   -3,  /* (15) tex_prop ::= SCALE num SEMICOLON */
   -3,  /* (16) tex_prop ::= TEXELOFFSETS int SEMICOLON */
   -4,  /* (17) tex_prop ::= OFFSET num num SEMICOLON */
   -4,  /* (18) tex_prop ::= FILTERING str str SEMICOLON */
   -3,  /* (19) tex_prop ::= MAX_ANISOTROPY num SEMICOLON */
   -1,  /* (20) str ::= STR */
   -1,  /* (21) int ::= INT */
   -1,  /* (22) num ::= FLOAT */
   -1,  /* (23) num ::= INT */
   -1,  /* (24) start ::= definitions */
    0,  /* (25) definitions ::= */
   -2,  /* (26) definitions ::= definitions def */
    0,  /* (27) shader_props ::= */
   -2,  /* (28) shader_props ::= shader_props shader_prop */
   -3,  /* (29) shader_prop ::= shader_sourcetype shader_sources SEMICOLON */
   -1,  /* (30) shader_sources ::= shader_src */
   -2,  /* (31) shader_sources ::= shader_sources shader_src */
   -1,  /* (32) def ::= COLON */
    0,  /* (33) mat_props ::= */
   -2,  /* (34) mat_props ::= mat_props mat_prop */
    0,  /* (35) tex_props ::= */
   -2,  /* (36) tex_props ::= tex_props tex_prop */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  NTEXTURE_ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  NTEXTURE_ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  NTEXTURE_ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* def ::= shader_name L_BRACE shader_props R_BRACE */
#line 64 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    if (rendermode == render_opengl)
      d->p->Link();
  }
#line 1028 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,1,&yymsp[-2].minor);
  yy_destructor(yypParser,2,&yymsp[0].minor);
        break;
      case 1: /* shader_name ::= SHADER str */
{  yy_destructor(yypParser,3,&yymsp[-1].minor);
#line 70 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    if (rendermode == render_opengl)
      d->p = shaderprogs.Get(yymsp[0].minor.yy10);
  }
#line 1039 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
}
        break;
      case 2: /* shader_sourcetype ::= V_SOURCE */
{  yy_destructor(yypParser,5,&yymsp[0].minor);
#line 80 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{ d->vertex_src = true; }
#line 1046 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
}
        break;
      case 3: /* shader_sourcetype ::= F_SOURCE */
{  yy_destructor(yypParser,6,&yymsp[0].minor);
#line 81 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{ d->vertex_src = false; }
#line 1053 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
}
        break;
      case 4: /* shader_src ::= str */
#line 87 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    if (rendermode == render_opengl)
    {
      Shader *s = shaders.Find(yymsp[0].minor.yy10); // cannot use Get because Shader constructor needs type as parameter
      if (!s)
      {
	s = new Shader(yymsp[0].minor.yy10, d->vertex_src); // construct and compile
	shaders.Insert(s);
      }

      d->p->AttachShader(s); // attach a source module to the shader
    }
  }
#line 1071 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
        break;
      case 5: /* def ::= mat_type mat_name L_BRACE mat_props R_BRACE */
#line 108 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    // Material definition finished
    if (d->m)
    {
      if (d->m->tex.size() < 1)
	I_Error("No textures given."); // FIXME proper check

      CONS_Printf(" Built material '%s'.\n", d->m->GetName());
      d->m->InitializeMaterial();
    }
  }
#line 1086 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,1,&yymsp[-2].minor);
  yy_destructor(yypParser,2,&yymsp[0].minor);
        break;
      case 6: /* mat_type ::= MATERIAL */
{  yy_destructor(yypParser,7,&yymsp[0].minor);
#line 120 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{ d->is_sprite = false; }
#line 1094 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
}
        break;
      case 7: /* mat_type ::= SPRITE */
{  yy_destructor(yypParser,8,&yymsp[0].minor);
#line 121 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{ d->is_sprite = true; }
#line 1101 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
}
        break;
      case 8: /* mat_name ::= str */
#line 124 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    d->m = materials.Edit(yymsp[0].minor.yy10, d->is_sprite ? TEX_sprite : TEX_wall, true);
    d->texeloffsets = false;
    d->tex_unit = 0;
  }
#line 1111 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
        break;
      case 9: /* mat_prop ::= SHADER_REF str SEMICOLON */
{  yy_destructor(yypParser,10,&yymsp[-2].minor);
#line 137 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    if (rendermode == render_opengl)
    {
      ShaderProg *p = shaderprogs.Find(yymsp[-1].minor.yy10);
      if (p)
        d->m->shader = p;
      else
        CONS_Printf(" Unknown shader '%s'.\n", yymsp[-1].minor.yy10);
    }
  }
#line 1126 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,4,&yymsp[0].minor);
}
        break;
      case 10: /* mat_prop ::= tex_unit L_BRACE tex_props R_BRACE */
#line 149 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    d->tex_unit++;
  }
#line 1135 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,1,&yymsp[-2].minor);
  yy_destructor(yypParser,2,&yymsp[0].minor);
        break;
      case 11: /* tex_unit ::= TEX_UNIT */
{  yy_destructor(yypParser,11,&yymsp[0].minor);
#line 154 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    int units = d->m->tex.size();
    if (units <= d->tex_unit)
      d->m->tex.resize(d->tex_unit+1);
    d->tr = &d->m->tex[d->tex_unit];
  }
#line 1148 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
}
        break;
      case 12: /* tex_prop ::= TEXTURE str SEMICOLON */
{  yy_destructor(yypParser,12,&yymsp[-2].minor);
#line 165 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    Texture *tex = textures.Get(yymsp[-1].minor.yy10);
    d->tr->t = tex;
  }
#line 1158 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,4,&yymsp[0].minor);
}
        break;
      case 13: /* tex_prop ::= WORLDSIZE num num SEMICOLON */
{  yy_destructor(yypParser,13,&yymsp[-3].minor);
#line 171 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    if (d->tr->t)
    {
      d->tr->xscale = d->tr->t->width / yymsp[-2].minor.yy1;
      d->tr->yscale = d->tr->t->height / yymsp[-1].minor.yy1;
    }
  }
#line 1172 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,4,&yymsp[0].minor);
}
        break;
      case 14: /* tex_prop ::= SCALE num num SEMICOLON */
{  yy_destructor(yypParser,14,&yymsp[-3].minor);
#line 178 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{ d->tr->yscale = 1.0/yymsp[-2].minor.yy1; d->tr->xscale = d->tr->yscale/yymsp[-1].minor.yy1; }
#line 1180 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,4,&yymsp[0].minor);
}
        break;
      case 15: /* tex_prop ::= SCALE num SEMICOLON */
{  yy_destructor(yypParser,14,&yymsp[-2].minor);
#line 179 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{ d->tr->xscale = d->tr->yscale = 1.0/yymsp[-1].minor.yy1; }
#line 1188 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,4,&yymsp[0].minor);
}
        break;
      case 16: /* tex_prop ::= TEXELOFFSETS int SEMICOLON */
{  yy_destructor(yypParser,15,&yymsp[-2].minor);
#line 180 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{ d->texeloffsets = yymsp[-1].minor.yy34; }
#line 1196 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,4,&yymsp[0].minor);
}
        break;
      case 17: /* tex_prop ::= OFFSET num num SEMICOLON */
{  yy_destructor(yypParser,16,&yymsp[-3].minor);
#line 182 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    if (d->tr->t)
      if (d->texeloffsets)
        {
	  d->tr->t->leftoffs = int(yymsp[-2].minor.yy1 / d->tr->xscale);
	  d->tr->t->topoffs = int(yymsp[-1].minor.yy1 / d->tr->yscale);
	}
      else
        {
	  d->tr->t->leftoffs = int(yymsp[-2].minor.yy1);
	  d->tr->t->topoffs = int(yymsp[-1].minor.yy1);
	}
  }
#line 1216 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,4,&yymsp[0].minor);
}
        break;
      case 18: /* tex_prop ::= FILTERING str str SEMICOLON */
{  yy_destructor(yypParser,17,&yymsp[-3].minor);
#line 197 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    d->tr->mag_filter = (toupper(yymsp[-2].minor.yy10[0]) == 'L') ? GL_LINEAR : GL_NEAREST;
    int temp;
    bool min_linear = (toupper(yymsp[-1].minor.yy10[0]) == 'L');
    switch (toupper(yymsp[-1].minor.yy10[1]))
      {
      case 'L':
	temp = min_linear ? GL_LINEAR_MIPMAP_LINEAR : GL_NEAREST_MIPMAP_LINEAR; break;
      case 'N':
	temp = min_linear ? GL_LINEAR_MIPMAP_NEAREST : GL_NEAREST_MIPMAP_NEAREST; break;
      default:
	temp = min_linear ? GL_LINEAR : GL_NEAREST; break;
      }

    d->tr->min_filter = temp;
  }
#line 1239 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,4,&yymsp[0].minor);
}
        break;
      case 19: /* tex_prop ::= MAX_ANISOTROPY num SEMICOLON */
{  yy_destructor(yypParser,18,&yymsp[-2].minor);
#line 215 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
    d->tr->max_anisotropy = yymsp[-1].minor.yy1;
  }
#line 1249 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,4,&yymsp[0].minor);
}
        break;
      case 20: /* str ::= STR */
#line 220 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{ yylhsminor.yy10 = yymsp[0].minor.yy0.stype; }
#line 1256 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yymsp[0].minor.yy10 = yylhsminor.yy10;
        break;
      case 21: /* int ::= INT */
#line 223 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{ yylhsminor.yy34 = yymsp[0].minor.yy0.itype; }
#line 1262 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yymsp[0].minor.yy34 = yylhsminor.yy34;
        break;
      case 22: /* num ::= FLOAT */
#line 226 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{ yylhsminor.yy1 = yymsp[0].minor.yy0.ftype; }
#line 1268 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yymsp[0].minor.yy1 = yylhsminor.yy1;
        break;
      case 23: /* num ::= INT */
#line 227 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{ yylhsminor.yy1 = yymsp[0].minor.yy0.itype; }
#line 1274 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yymsp[0].minor.yy1 = yylhsminor.yy1;
        break;
      case 29: /* shader_prop ::= shader_sourcetype shader_sources SEMICOLON */
#line 78 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
}
#line 1281 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
  yy_destructor(yypParser,4,&yymsp[0].minor);
        break;
      case 32: /* def ::= COLON */
{  yy_destructor(yypParser,9,&yymsp[0].minor);
#line 130 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"
{
}
#line 1289 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
}
        break;
      default:
      /* (24) start ::= definitions */ yytestcase(yyruleno==24);
      /* (25) definitions ::= */ yytestcase(yyruleno==25);
      /* (26) definitions ::= definitions def */ yytestcase(yyruleno==26);
      /* (27) shader_props ::= */ yytestcase(yyruleno==27);
      /* (28) shader_props ::= shader_props shader_prop */ yytestcase(yyruleno==28);
      /* (30) shader_sources ::= shader_src (OPTIMIZED OUT) */ assert(yyruleno!=30);
      /* (31) shader_sources ::= shader_sources shader_src */ yytestcase(yyruleno==31);
      /* (33) mat_props ::= */ yytestcase(yyruleno==33);
      /* (34) mat_props ::= mat_props mat_prop */ yytestcase(yyruleno==34);
      /* (35) tex_props ::= */ yytestcase(yyruleno==35);
      /* (36) tex_props ::= tex_props tex_prop */ yytestcase(yyruleno==36);
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  NTEXTURE_ParseARG_FETCH
  NTEXTURE_ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 31 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"

  fprintf(stderr,"Giving up.  Parser is hopelessly lost...\n");
#line 1348 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
/************ End %parse_failure code *****************************************/
  NTEXTURE_ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  NTEXTURE_ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  NTEXTURE_ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  NTEXTURE_ParseARG_FETCH
  NTEXTURE_ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
/************ End %syntax_error code ******************************************/
  NTEXTURE_ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  NTEXTURE_ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  NTEXTURE_ParseARG_FETCH
  NTEXTURE_ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
#line 27 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.y"

  fprintf(stderr, "Parsing complete!\n");
#line 1395 "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/grammars/ntexture.parser.c"
/*********** End %parse_accept code *******************************************/
  NTEXTURE_ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  NTEXTURE_ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "NTEXTURE_ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void NTEXTURE_Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  NTEXTURE_ParseTOKENTYPE yyminor       /* The value for the token */
  NTEXTURE_ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  NTEXTURE_ParseCTX_FETCH
  NTEXTURE_ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  while(1){ /* Exit by "break" */
    assert( yypParser->yytos>=yypParser->yystack );
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      unsigned int yyruleno = yyact - YY_MIN_REDUCE; /* Reduce by this rule */
#ifndef NDEBUG
      assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
      if( yyTraceFILE ){
        int yysize = yyRuleInfoNRhs[yyruleno];
        if( yysize ){
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
            yyTracePrompt,
            yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
            yypParser->yytos[yysize].stateno);
        }else{
          fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
            yyTracePrompt, yyruleno, yyRuleName[yyruleno],
            yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
        }
      }
#endif /* NDEBUG */

      /* Check that the stack is large enough to grow by a single entry
      ** if the RHS of the rule is empty.  This ensures that there is room
      ** enough on the stack to push the LHS value */
      if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
        if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
          yypParser->yyhwm++;
          assert( yypParser->yyhwm ==
                  (int)(yypParser->yytos - yypParser->yystack));
        }
#endif
#if YYSTACKDEPTH>0 
        if( yypParser->yytos>=yypParser->yystackEnd ){
          yyStackOverflow(yypParser);
          break;
        }
#else
        if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
          if( yyGrowStack(yypParser) ){
            yyStackOverflow(yypParser);
            break;
          }
        }
#endif
      }
      yyact = yy_reduce(yypParser,yyruleno,yymajor,yyminor NTEXTURE_ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos > yypParser->yystack ){
          yyact = yy_find_reduce_action(yypParser->yytos->stateno,
                                        YYERRORSYMBOL);
          if( yyact<=YY_MAX_SHIFTREDUCE ) break;
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos <= yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int NTEXTURE_ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
