// Emacs style mode select   -*- C++ -*-
//-----------------------------------------------------------------------------
//
// $Id: d_main.cpp 1108 2014-05-17 16:57:46Z smite-meister $
//
// Copyright (C) 1993-1996 by id Software, Inc.
// Copyright (C) 1998-2008 by DooM Legacy Team.
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
//-----------------------------------------------------------------------------

/// \file
/// \brief Startup and initialization (D_DoomMain),
/// game loop (D_DoomLoop), event system.

#include <sys/stat.h>
#include <unistd.h>

#ifdef SDL2
#include <SDL2/SDL.h>
#endif

#include "command.h"
#include "console.h"

#include "d_event.h"
#include "doomdef.h"
#include "g_game.h"
#include "g_input.h"

#include "i_sound.h"
#include "i_system.h"
#include "i_video.h"
#include "screen.h"

#include "m_argv.h"
#include "m_menu.h"
#include "menu/menudef.h"
#include "m_misc.h" // configfile

#include "s_sound.h"
#include "sounds.h"
#include "z_ascache.h"
#include "r_data.h"

#include "g_actor.h"
#include "g_player.h"
#include "g_pawn.h"

#include "interfaces/i_game_backend.h"

#include "doomdata.h"

#include "w_wad.h"
#include "z_zone.h"
#include "m_fixed.h"

void GenerateTables();
void SV_Init();
void CL_Init();
void PrepareGameData();

#ifndef SVN_REV
#define SVN_REV "none"
#endif

// Version number: major.minor.revision
const int LEGACY_VERSION = 200; // major*100 + minor
const int LEGACY_REVISION = 0;  // for bugfix releases, should not affect compatibility
const char LEGACY_VERSIONSTRING[] = "alpha0 (rev " SVN_REV ")";
char LEGACY_VERSION_BANNER[80];

// Name of local directory for config files and savegames
#ifdef LINUX
#define DEFAULTDIR "/.legacy"
#elif defined(__MACOS__) || defined(__APPLE_CC__)
#define DEFAULTDIR "/Library/Application Support/DooMLegacy"
#else
#define DEFAULTDIR "/legacy"
#endif

// the file where all game vars and settings are saved
#define CONFIGFILENAME "config.cfg"

bool devparm = false;    // started game with -devparm
bool singletics = false; // timedemo

// "Mission packs". Used only during startup.
enum gamemission_t
{
    gmi_shareware, // DOOM 1 shareware (E1M9)
    gmi_doom1,     // registered (E3M27)
    gmi_ultimate,  // retail (Ultimate DOOM) (E4M36)
    gmi_doom2,     // DOOM 2, default
    gmi_tnt,       // TNT Evilution mission pack
    gmi_plut,      // Plutonia Experiment pack
    gmi_heretic,
    gmi_hexen
};

static gamemission_t mission = gmi_doom2;

// Autoload functionality
#define MAX_AUTOLOAD_FILES 32
static char *autoload_files[MAX_AUTOLOAD_FILES];
static int num_autoload_files = 0;
static bool autoload_frozen = false; // true once file cache is built; ignores further autoload cmds

// Add a file to the autoload list (called from sv_cmds.cpp via extern declaration)
void D_AddAutoloadFile(const char *file)
{
    if (autoload_frozen)
    {
        CONS_Printf("autoload: '%s' ignored (file cache already built)\n", file);
        return;
    }

    if (num_autoload_files >= MAX_AUTOLOAD_FILES)
    {
        CONS_Printf("Too many autoload files (max %d)\n", MAX_AUTOLOAD_FILES);
        return;
    }

    char *newfile = (char *)malloc(strlen(file) + 1);
    strcpy(newfile, file);
    autoload_files[num_autoload_files++] = newfile;
}

// Resolve path variables like $PROGDIR
static char *D_ResolveAutoloadPath(const char *path)
{
    static char resolved_path[1024];

    if (path[0] == '$')
    {
        if (!strncmp(path, "$PROGDIR", 8))
        {
            // Get the directory where the executable is located
#ifdef SDL2
            char *basepath = SDL_GetBasePath();
            snprintf(resolved_path, sizeof(resolved_path), "%s%s",
                     basepath ? basepath : "", path + 8);
            if (basepath)
                SDL_free(basepath);
#else
            snprintf(resolved_path, sizeof(resolved_path), "%s", path + 8);
#endif
            return resolved_path;
        }
        // Add other path variables here if needed
    }

    // No variable to resolve, return as-is
    return (char *)path;
}

// Helper function: start a new game
void BeginGame(int episode, int skill, bool public_server)
{
    if (public_server)
        COM.AppendText(va("newgame %s server %d %d\n", game.mapinfo_lump.c_str(), episode, skill));
    else
        COM.AppendText(va("newgame %s local %d %d\n", game.mapinfo_lump.c_str(), episode, skill));
}

//======================================================================
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
// referenced from i_system.c for I_GetKey()
//======================================================================

event_t events[MAXEVENTS];
int eventhead = 0;
int eventtail = 0;

// FPS limiter CVar
static CV_PossibleValue_t fpslimit_cons_t[] = {
    {0,"Uncapped"},{35,"35"},{60,"60"},{120,"120"},{144,"144"},{240,"240"},{0,NULL}
};
consvar_t cv_fpslimit = {"fpslimit","0", CV_SAVE, fpslimit_cons_t, NULL};

bool shiftdown = false, altdown = false;

//
// Called by the I/O functions when input is detected
//
void D_PostEvent(const event_t *ev)
{
    events[eventhead] = *ev;
    eventhead = (eventhead + 1) & (MAXEVENTS - 1);
}

//
// Send all the events of the given timestamp down the responder chain
//
void D_ProcessEvents()
{
    for (; eventtail != eventhead; eventtail = (eventtail + 1) & (MAXEVENTS - 1))
    {
        event_t *ev = &events[eventtail];

        if (game.dedicated)
            con.Responder(ev); // dedicated server only has a console interface
        else
        {
            // Console toggle key always wins — even over open menus.
            // Exception: KEY_BACKSPACE is bound as a fallback toggle for non-US keyboards,
            // but when the console is already active it must reach the text-editing handler.
            if (ev->type == ev_keydown)
            {
                int key = ev->data1;
                if (key == commoncontrols[gk_console][0] || key == commoncontrols[gk_console][1])
                {
                    if (con.IsOpen() && key == KEY_BACKSPACE)
                        ; // fall through — let con.Responder handle it as a delete
                    else
                    {
                        con.Toggle();
                        continue;
                    }
                }
            }
            // Menu input
            if (Menu::Responder(ev))
                continue; // menu ate the event
            // console input
            if (con.Responder(ev))
                continue; // ate the event
            game.Responder(ev);
        }
    }
}

// =========================================================================
//   D_DoomLoop
// =========================================================================

void D_DoomLoop()
{
    // timekeeping for the game
    tic_t rendertimeout = 0;     // next time the screen MUST be updated
    tic_t rendertic = 0;         // last rendered gametic
    tic_t oldtics = I_GetTics(); // current time

    // main game loop
    while (1)
    {
#ifdef SDL2
        Uint32 frame_start = SDL_GetTicks();
#endif

        // How much time has elapsed?
        tic_t now = I_GetTics();
        tic_t elapsed = now - oldtics;
        oldtics = now;

        // give time to the OS
        if (elapsed == 0)
        {
            I_Sleep(1);
            continue;
        }

#ifdef HW3SOUND
        HW3S_BeginFrameUpdate();
#endif

        // run tickers, advance game state
        game.TryRunTics(elapsed);

        if (!game.dedicated)
        {
            if (singletics || game.tic > rendertic)
            {
                // render if gametics have passed since last rendering
                rendertic = game.tic;
                rendertimeout = now + TICRATE / 17;

                // Update listener (player) position for 3D audio
                if (ViewPlayers.size() > 0 && ViewPlayers[0]->pawn)
                {
                    PlayerPawn *p = ViewPlayers[0]->pawn;
                    // Position (fixed-point to float conversion using Float() method)
                    float px = p->pos.x.Float();
                    float py = p->pos.y.Float();
                    float pz = p->pos.z.Float();
                    // Velocity (for Doppler effect)
                    float vx = p->vel.x.Float();
                    float vy = p->vel.y.Float();
                    float vz = p->vel.z.Float();
                    // Forward direction (facing)
                    float fx = 0, fy = 0, fz = -1; // Simplified - would need actual yaw/pitch
                    float ux = 0, uy = 1, uz = 0;  // Up direction

                    I_SetListenerPosition(px, py, pz, vx, vy, vz, fx, fy, fz, ux, uy, uz);
                }

                // move positional sounds, adjust volumes
                S.UpdateSounds();
                // Update display, next frame, with current state.
                game.Display();
            }
            else if (rendertimeout < now)
            {
                // otherwise render if enough real time has elapsed since last rendering
                // in case the server hang or netsplit
                game.Display();
            }
        }

        // Process async resource loading completions (single call per frame)
        if (cv_async_loading.value)
            AsyncCache_ProcessCompletions();

        // check for media change, loop music..
        I_UpdateCD();

#ifdef HW3SOUND
        HW3S_EndFrameUpdate();
#endif

#ifdef SDL2
        // FPS limiter: sleep remainder of the frame budget if a cap is set
        if (cv_fpslimit.value > 0)
        {
            Uint32 target_ms = 1000 / (Uint32)cv_fpslimit.value;
            Uint32 elapsed_ms = SDL_GetTicks() - frame_start;
            if (elapsed_ms < target_ms)
                SDL_Delay(target_ms - elapsed_ms);
        }
#endif
    }
}

//
// D_AddFile
//
static char *startupwadfiles[MAX_WADFILES];

static void D_AddFile(const char *file)
{
    static int i = 0;

    CONS_Printf(" D_AddFile: queuing '%s'\n", file);

    if (i >= MAX_WADFILES)
        return;

    char *newfile = (char *)malloc(strlen(file) + 1);
    strcpy(newfile, file);

    startupwadfiles[i++] = newfile;
}

// ==========================================================================
// Identify the Doom version, and IWAD file to use.
// Sets 'game.mode' to determine whether registered/commmercial features are
// available (notable loading PWAD files).
// ==========================================================================

// Decide between Doom or Ultimate Doom, use size to detect which one
static gamemission_t D_GetDoomType(const char *wadname)
{
    struct stat sbuf;
    // Fab: and if I patch my main wad and the size gets
    // bigger ? uh?
    // BP: main wad MUST not be patched !
    stat(wadname, &sbuf);
    if (sbuf.st_size < 12408292)
        return gmi_doom1;
    else
        return gmi_ultimate; // Ultimate
}

// identifies the iwad used
static void D_IdentifyVersion()
{
    // Specify the name of an IWAD file to use.
    // Internally the game makes no difference between IWADs and PWADs.
    // Non-free files are just not offered for upload in network games.
    // The -iwad parameter just means that we MUST have this wad file
    // in order to continue. It is also loaded right after legacy.wad.

#define NUM_IWADS 9
    struct
    {
        const char *wadname;
        gamemode_t mode;
        gamemission_t mission;
    } iwads[NUM_IWADS] = {
        // order of preference
        {"doom2.wad", gm_doom2, gmi_doom2},
        {"doomu.wad", gm_doom1, gmi_ultimate},
        {"doom.wad", gm_doom1, gmi_doom1},
        {"heretic.wad", gm_heretic, gmi_heretic},
        {"hexen.wad", gm_hexen, gmi_hexen},
        {"tnt.wad", gm_doom2, gmi_tnt},
        {"plutonia.wad", gm_doom2, gmi_plut},
        {"doom1.wad", gm_doom1, gmi_shareware},
        {"heretic1.wad", gm_heretic, gmi_heretic},
    };

    // default
    game.mode = gm_doom2;
    mission = gmi_doom2;

    if (M_CheckParm("-iwad"))
    {
        const char *s = M_GetNextParm();
        const char *found_path = NULL;

        // First try the path as specified
        if (fc.Access(s))
        {
            found_path = s;
        }
        else
        {
            // If not found, try relative to the executable directory
#ifdef SDL2
            char *basepath = SDL_GetBasePath();
            if (basepath)
            {
                static char exe_path[1024];
                // Build path: basepath + "/" + filename
                strcpy(exe_path, basepath);
                strcat(exe_path, "/");
                strcat(exe_path, s);
                if (fc.Access(exe_path))
                {
                    found_path = exe_path;
                }
                SDL_free(basepath);
            }
#endif
        }

        if (!found_path)
            I_Error("IWAD %s not found!\n", s);

        D_AddFile(found_path);

        // point to start of filename only
        s = FIL_StripPath(s);

        // try to find implied gamemode
        for (int i = 0; i < NUM_IWADS; i++)
            if (!strcasecmp(s, iwads[i].wadname))
            {
                game.mode = iwads[i].mode;
                mission = iwads[i].mission;
                break;
            }

        // Ultimate doom or not?
        if (mission == gmi_doom1)
            mission = D_GetDoomType(s);
    }
    // TODO perhaps we should not try to find a wadfile here, rather
    // start the game without any preloaded wadfiles other than legacy.wad
    else // finally we'll try to find a wad file by ourselves
    {
        int i;
        // try to find implied gamemode
        for (i = 0; i < NUM_IWADS; i++)
            if (fc.Access(iwads[i].wadname))
            {
                D_AddFile(iwads[i].wadname);
                game.mode = iwads[i].mode;
                mission = iwads[i].mission;
                break;
            }

        if (i == NUM_IWADS)
        {
            I_Error("Main IWAD file not found.\n"
                    "You need either doom.wad, doom1.wad, doomu.wad, doom2.wad,\n"
                    "tnt.wad, plutonia.wad, heretic.wad, heretic1.wad or hexen.wad\n"
                    "from any shareware or commercial version of Doom, Heretic or Hexen!\n");
        }
    }

    // should we enable inventory?
    game.inventory = (game.mode >= gm_heretic);
}

// ========================================================================
// Just print the nice red titlebar like the original DOOM2 for DOS.
// ========================================================================
#ifdef PC_DOS
void D_Titlebar(char *title1, char *title2)
{
    // DOOM LEGACY banner
    clrscr();
    textattr((BLUE << 4) + WHITE);
    clreol();
    cputs(title1);

    // standard doom/doom2 banner
    textattr((RED << 4) + WHITE);
    clreol();
    gotoxy((80 - strlen(title2)) / 2, 2);
    cputs(title2);
    normvideo();
    gotoxy(1, 3);
}
#endif

//
//  Center the title string, then add the date and time of compilation.
//
static const char *D_MakeTitleString(const char *s)
{
    static char banner[81];
    memset(banner, ' ', sizeof(banner));

    int i;

    for (i = (80 - strlen(s)) / 2; *s;)
        banner[i++] = *s++;

    const char *u = __DATE__;
    for (i = 0; i < 11; i++)
        banner[i + 1] = u[i];

    u = __TIME__;
    for (i = 0; i < 8; i++)
        banner[i + 71] = u[i];

    banner[80] = '\0';
    return banner;
}

static void D_CheckWadVersion()
{
    // check version of legacy.wad using version lump
    int wadversion = 0;
    int lump = fc.FindNumForName("VERSION", true);
    if (lump != -1)
    {
        char s[128];
        int l = fc.ReadLumpHeader(lump, s, 127);
        s[l] = '\0';
        if (sscanf(s, "Doom Legacy WAD v%d.%d.%*d", &l, &wadversion) == 2)
            wadversion += l * 100;
    }

    if (wadversion != LEGACY_VERSION)
        I_Error("Your legacy.wad file is version %d.%d, you need version %d.%d\n"
                "Use the legacy.wad coming from the same zip file as this executable\n"
                "\n"
                "Use -noversioncheck to remove this check,\n"
                "but this can cause Legacy to crash\n",
                wadversion / 100,
                wadversion % 100,
                LEGACY_VERSION / 100,
                LEGACY_VERSION % 100);
}

// set up correct paths to wads, configfiles and saves
void D_SetPaths()
{
    const char *wadpath = getenv("DOOMWADDIR");
    if (!wadpath)
        wadpath = I_GetWadPath();

    // store the wad path
    fc.SetPath(wadpath);

    char *userhome;

    if (M_CheckParm("-home") && M_IsNextParm())
        userhome = M_GetNextParm();
    else
        userhome = getenv("HOME");

#ifdef LINUX // user home directory
    if (!userhome)
        I_Error("Please set $HOME to your home directory\n");
#endif

    string legacyhome = ".";

    if (userhome)
    {
        // use user specific config files and saves
        legacyhome = string(userhome);
        legacyhome += DEFAULTDIR; // config files, saves here
        I_mkdir(legacyhome.c_str(), S_IRWXU);
    }

    // check for a custom config file
    if (M_CheckParm("-config") && M_IsNextParm())
    {
        strcpy(configfile, M_GetNextParm());
        CONS_Printf("Using config file '%s'\n", configfile);
    }
    else
    {
        // little hack to allow a different config file for opengl
        // may be a problem if opengl cannot really be started
        if (M_CheckParm("-opengl"))
            sprintf(configfile, "%s/gl" CONFIGFILENAME, legacyhome.c_str());
        else
            sprintf(configfile, "%s/" CONFIGFILENAME, legacyhome.c_str());
    }

    // savegame name templates
    sprintf(savegamename, "%s/%s", legacyhome.c_str(), "savegame_%d.sav");
    sprintf(hubsavename, "%s/%s", legacyhome.c_str(), "hubsave_%02d.sav");
}

//
// D_DoomMain
//
bool D_DoomMain()
{
    sprintf(LEGACY_VERSION_BANNER,
            "Doom Legacy %d.%d.%d %s",
            LEGACY_VERSION / 100,
            LEGACY_VERSION % 100,
            LEGACY_REVISION,
            LEGACY_VERSIONSTRING);

    if (M_CheckParm("--version"))
    {
        printf("%s\n", D_MakeTitleString(LEGACY_VERSION_BANNER));
        return false;
    }

    // TODO: Better commandline help
    if (M_CheckParm("--help") || M_CheckParm("-h"))
    {
        printf("%s\n", D_MakeTitleString(LEGACY_VERSION_BANNER));
        printf("Usage: legacy [-opengl] [-newui] [-iwad xxx.wad] [-file pwad.wad stuff.zip ...] "
               "[-warp <map>] [-skill <1-5>]\n");
        return false;
    }

    // we need to check for dedicated before initialization of some subsystems
    game.dedicated = M_CheckParm("-dedicated");

    // keep error messages until the final flush(stderr)
    // if (setvbuf(stderr,NULL,_IOFBF,1000)) CONS_Printf("setvbuf didnt work\n");
    if (!game.dedicated)
    {
        // FIXME: these files should be placed in ~/Library/Logs/ as Legacy_%s.log
#ifndef __APPLE_CC__
        // Enable log files for debugging
        if (freopen("stdout.txt", "w", stdout) == NULL)
            CONS_Printf("freopen didnt work\n");
        if (freopen("stderr.txt", "w", stderr) == NULL)
            CONS_Printf("freopen didnt work\n");
#endif
    }

    setbuf(stdout, NULL); // non-buffered output

    // start console output by the banner line
    CONS_Printf("%s\n", D_MakeTitleString(LEGACY_VERSION_BANNER));

    // get parameters from a response file (eg: legacy @parms.txt)
    // adds parameters found within file to myargc, myargv.
    M_FindResponseFile();

    Menu::SetNewUI(M_CheckParm("-newui"));

    // set up correct paths to wads, configfiles and saves
    D_SetPaths();

    // external Legacy data file (load it before iwad!)
    // Make it optional - if it doesn't exist, continue without it
    if (fc.Access("legacy.wad"))
        D_AddFile("legacy.wad");
    if (fc.Access("legacy_ui.pk3"))
        D_AddFile("legacy_ui.pk3");

    // identify the main IWAD file to use (if any),
    // set game.mode, mission accordingly
    D_IdentifyVersion();

    // Early config loading for autoload support
    //------------------------------------- CONFIG.CFG (after IWAD identification)
    // We need to load config after IWAD but before file cache init
    {
        // command buffer (needed for config loading)
        COM.Init();

        // system-specific stuff (needed for some config vars)
        I_SysInit();

        // generate a couple of lookup tables (needed before SV_Init)
        GenerateTables();

        // Server init (registers autoload command; R_ServerInit moved to after file cache)
        SV_Init();

        // NOTE: CL_Init is intentionally NOT called here.
        // CL_Init calls vid.Startup/R_Init/con.Init which all require the file cache.
        // It is called after fc.InitMultipleFiles below.

        // Load config early to collect autoload entries.
        // Client CVars (video, input, etc.) are not yet registered, so they
        // will be applied on the second M_FirstLoadConfig call below.
        M_FirstLoadConfig(); // WARNING : this does a "COM_BufExecute()"
    }

    // game title
    const char *Titles[] = {//"No game mode chosen.",
                            "DOOM Shareware Startup",
                            "DOOM Registered Startup",
                            "The Ultimate DOOM Startup",
                            "DOOM 2: Hell on Earth",
                            "DOOM 2: TNT - Evilution",
                            "DOOM 2: Plutonia Experiment",
                            "Heretic: Shadow of the Serpent Riders",
                            "Hexen: Beyond Heretic"};

    const char *title = Titles[mission];

    // print out game title
    CONS_Printf("%s\n\n", title);

    // "developement parameter"
    devparm = M_CheckParm("-devparm");
    if (devparm)
        CONS_Printf("Development mode on.\n");

    // add any files specified on the command line with -file to the wad list
    // Support multiple -file flags: -file a.pk3 -file b.pk3
    CONS_Printf("Scanning %d argv for -file flags\n", myargc);
    for (int p = 1; p < myargc; p++)
    {
        CONS_Printf(" argv[%d] = '%s'\n", p, myargv[p]);
        if (!strcasecmp(myargv[p], "-file"))
        {
            for (p++; p < myargc && myargv[p][0] != '-' && myargv[p][0] != '+'; p++)
                D_AddFile(myargv[p]);
            p--; // outer loop will increment again
        }
    }

    // Load autoload files into startup list (before file cache initialization)
    for (int i = 0; i < num_autoload_files; i++)
    {
        char *resolved_path = D_ResolveAutoloadPath(autoload_files[i]);
        CONS_Printf("Autoloading %s\n", resolved_path);
        D_AddFile(resolved_path);
        free(autoload_files[i]);
    }
    num_autoload_files = 0;
    // Freeze autoload list: the file cache is about to be built.
    // Any autoload commands from the second M_FirstLoadConfig call will be ignored.
    autoload_frozen = true;

    //========================== continue subsystem initializations ==========================

    // memory management
    Z_Init();

    // file cache
    if (!fc.InitMultipleFiles(startupwadfiles))
        I_Error("A WAD file was not found\n");

    // see that legacy.wad version matches program version (only if legacy.wad was loaded)
    if (!M_CheckParm("-noversioncheck") && fc.FindNumForName("VERSION", true) != -1)
        D_CheckWadVersion();

    // Initialize renderer data (textures, sprites) now that the file cache is ready.
    // R_ServerInit was removed from SV_Init because SV_Init is called early (before
    // the file cache) to register CVars for config loading.
    extern void R_ServerInit();
    R_ServerInit();

    // Start async resource loader after file cache is ready
    AsyncCache_Init();

    // Now that the file cache is ready, initialize the client subsystems.
    // This was intentionally omitted from the early block above.
    if (!game.dedicated)
        CL_Init();

    // Second config load: all CVars (including client CVars from CL_Init) are now
    // registered, so saved video/input/sound settings are properly applied.
    // autoload commands are silently ignored this time (autoload_frozen = true).
    M_FirstLoadConfig();

    // Convert old static game data structures into dynamic ones.
    // DEHACKED patches etc. must be applied before this.
    PrepareGameData();

    if (!game.dedicated)
    {
        // set user default mode or mode set at cmdline
        vid.CheckDefaultMode();
    }

    // ------------- starting the game ----------------

    const char *m;

    if (fc.FindNumForName("MAPINFO") >= 0)
        m = "MAPINFO";
    else
        switch (game.mode)
        {
            case gm_hexen:
                I_Error("No MAPINFO lump found!\n");
                break;
            case gm_heretic:
                m = "MI_HTIC";
                break;
            case gm_doom2:
                if (mission == gmi_tnt)
                    m = "MI_TNT";
                else if (mission == gmi_plut)
                    m = "MI_PLUT";
                else
                    m = "MI_DOOM2";
                break;
            default:
                m = "MI_DOOM1";
        }

    game.mapinfo_lump = m;

    // Parse MENUDEF lumps (mod-declared menus) now that all WADs are loaded.
    MenuDef_LoadAll();

    bool public_server = game.dedicated || M_CheckParm("-server");
    bool autostart = public_server; // server starts automatically
    int episode = 1;
    skill_t sk = sk_medium;
    int warp_map = 0; // 0 means no warp specified

    // get skill / episode / warp (map number)

    int p = M_CheckParm("-skill");
    if (p && M_IsNextParm())
    {
        sk = skill_t(myargv[p + 1][0] - '1');
        autostart = true;
    }

    p = M_CheckParm("-episode");
    if (p && M_IsNextParm())
    {
        episode = myargv[p + 1][0] - '0';
        autostart = true;
    }

    // -warp <mapnumber>: skip directly to specified map, skipping menus
    p = M_CheckParm("-warp");
    if (p && M_IsNextParm())
    {
        // Warp directly to the specified map number
        warp_map = atoi(myargv[p + 1]);
        if (warp_map > 0)
        {
            autostart = true;
        }
    }

    p = M_CheckParm("-loadgame");
    if (p && M_IsNextParm())
        COM.AppendText(va("load %d\n", atoi(myargv[p + 1])));
    else if (autostart)
    {
        if (warp_map > 0)
        {
            // Direct warp to specific map - bypass the newgame command
            game.SV_SpawnServer(false);
            game.SV_StartGame(sk, warp_map, 0);
        }
        else
        {
            BeginGame(episode, sk, public_server);
        }
    }
    else
        game.StartIntro(); // start up intro loop

    // push all "+" parameter into the command buffer (they are not yet executed!)
    M_PushSpecialParameters();

    // user settings
    COM.AppendText("exec autoexec.cfg\n");

    // execute all the waiting commands in the buffer
    COM.BufExecute();

    // end of loading screen: CONS_Printf() will no more call FinishUpdate()
    con.refresh = false;
    // Always close the startup full-screen console; the -warp/autostart path skips StartIntro()
    // which normally does this. Safe to call even when StartIntro() already closed it (idempotent).
    con.Toggle(true);
    vid.SetMode(); // change video mode if needed, recalculate...
    return true;
}

//====================================================================
// IGameBackend adapter - delegates to global game state and functions
//====================================================================

/// \brief Adapter that implements IGameBackend by delegating to global functions.
/// \details This allows production code to use IGameBackend pointers while
///         still accessing the real game state. In tests, MockGameBackend
///         can be injected instead.
class GameBackendAdapter : public IGameBackend {
public:
    void runGameLoop() override {
        D_DoomLoop();
    }

    void advanceTics(int elapsed) override {
        game.TryRunTics(elapsed);
    }

    void setGameState(int state) override {
        game.SetState(static_cast<GameInfo::gamestate_t>(state));
    }

    void startIntro() override {
        game.StartIntro();
    }

    void advanceIntro() override {
        game.AdvanceIntro();
    }

    void pauseGame(bool on) override {
        game.Pause(on);
    }

    void updateDisplay() override {
        game.Display();
    }

    void drawFrame() override {
        game.Drawer();
    }

    bool spawnServer(bool force_mapinfo) override {
        return game.SV_SpawnServer(force_mapinfo);
    }

    bool isPlaying() override {
        return game.Playing();
    }

    void quit() override {
        I_Quit();
    }
};

// Global adapter instance
static GameBackendAdapter s_gameBackendAdapter;

/// \brief Get the global IGameBackend instance.
/// \details Returns an adapter pointing to the global game functions.
///         Production code should use this instead of directly calling globals.
IGameBackend* GetGlobalGameBackend() {
    return &s_gameBackendAdapter;
}
