# CMake generated Testfile for 
# Source directory: /home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk
# Build directory: /home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(fixed_t_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_fixed_t.exe")
set_tests_properties(fixed_t_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;409;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
add_test(fixed_t_catch2_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_fixed_catch2.exe")
set_tests_properties(fixed_t_catch2_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;415;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
add_test(save_load_unit_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_save_load_unit.exe")
set_tests_properties(save_load_unit_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;424;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
add_test(serialization_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_serialization.exe")
set_tests_properties(serialization_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;430;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
add_test(tnl_packet_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_tnl_packets.exe")
set_tests_properties(tnl_packet_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;441;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
add_test(actor_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_actor.exe")
set_tests_properties(actor_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;446;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
add_test(component_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_components.exe")
set_tests_properties(component_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;452;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
add_test(console_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_console.exe")
set_tests_properties(console_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;457;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
add_test(vector_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_vector.exe")
set_tests_properties(vector_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;462;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
add_test(demos_integration_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_demos_integration.exe")
set_tests_properties(demos_integration_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;468;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
add_test(network_integration_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_network_integration.exe")
set_tests_properties(network_integration_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;474;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
add_test(parity_tests "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/build-mingw/test_parity.exe")
set_tests_properties(parity_tests PROPERTIES  _BACKTRACE_TRIPLES "/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;480;add_test;/home/geoffrey/openclaw/workspace/doomlegacy-legacy2/legacy/trunk/CMakeLists.txt;0;")
subdirs("engine")
subdirs("video")
subdirs("util")
subdirs("net")
subdirs("interface")
subdirs("grammars")
subdirs("_deps/catch2-build")
